name: skin_muse
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/skinmuselogo.png

  fonts:
    - family: Inter_Bold
      fonts:
        - asset: assets/fonts/inter_bold.ttf
    - family: Inter_Light
      fonts:
        - asset: assets/fonts/inter_light.ttf
